
version: 2

sources:
   - name : PELOTON
     description: "The raw data file from Peloton"
     database: WORKOUTS
     schema: RAW_DATA
     tables:
       - name: PELOTON_WORKOUTS

models:
    - name: instructors
      description: "List of Instructors"
      columns:
          - name: instructor_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: classes
      description: "List of Classes taken at a specific time"
      columns:
          - name: class_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: class_titles
      description: "List of Classes"
      columns:
          - name: class_title_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: workouts
      description: "List of Classes attended"
      columns:
          - name: workout_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null


