
version: 2

sources:
   - name : PELOTON
     database: WORKOUTS
     schema: RAW_DATA
     tables:
       - name: PELOTON_WORKOUTS

models:
    - name: instructors
      description: "List of Instructors"
      columns:
          - name: instructor_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

